# SPDX-License-Identifier: GPL-2.0+
#
# Makefile - Lenovo Legion Go Handheld Console Controller driver
#
lenovo-lego-hid-y := lenovo-lego-hid-core.o lenovo-lego-hid-config.o
obj-$(CONFIG_LENOVO_LEGO_HID)	:= lenovo-lego-hid.o
